### ISSUE TITLE
Array.from() is incorrectly implemented.

### ISSUE THREAD

**Issue by rwaldron** [llafuente/class#1]
The Array.from() function's implementation does not match the ES6/native Array.from

A correct implementation looks like this: https://gist.github.com/3186576

**Comment by llafuente** [comment]
Hi rwldrn,

I totally miss that...

I dont beleive that ES6 Array.from and mine are the same... in fact I will rename mine to Array.ize

I do some test and I didnt get the expected results.

Example:

```
var obj = {x:1};
t.deepEqual(Array.from(obj), [ obj ], "object error");  //raise, You should check: isNan(len) -> throw
t.deepEqual(Array.ize(obj), [ obj ], "object error"); // ok
```

Thanks for the issue, It's better to be prepared for ES6 :)

**Comment by rwaldron** [comment]
That's a good solution :)
